name: Build gridss Docker image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Docker image tag, If omitted will use github short sha"
        required: false
        type: string

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/download-docker-resources

  build:
    needs: [pre-build]
    uses: Ultimagen/ugbio-utils/.github/workflows/docker-build-push.yml@main
    secrets: inherit
    with:
       git-repo: ${{ github.repository }}
       git-ref: ${{ github.ref_name }}
       docker-image: gridss
       docker-tag: ${{ inputs.image-tag }}
       artifact-name: docker-resources
       docker-target: gridss
