name: Build gridss Docker image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Docker image tag, If omitted will use github short sha"
        required: false
        type: string

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout
env:
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/55428976747/locations/global/workloadIdentityPools/devops-pool/providers/devops-pool-provider
  GCP_SERVICE_ACCOUNT: gcr-push-sa@ultima-data-307918.iam.gserviceaccount.com
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Install gsutil 
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Download resources
        run: |
          gsutil cp gs://concordance-data/scripts/RepeatMasker-4.1.2-p1.tar.gz RepeatMasker-4.1.2-p1.tar.gz
          gsutil cp gs://concordance-data/scripts/rmblast-2.14.1+-x64-linux.tar.gz rmblast-2.14.1+-x64-linux.tar.gz
          
      - name: Upload resources
        uses: actions/upload-artifact@v4
        with:
          name: docker-resources
          path: |
            RepeatMasker-4.1.2-p1.tar.gz
            rmblast-2.14.1+-x64-linux.tar.gz
          
  build:
    needs: [pre-build]
    uses: Ultimagen/ugbio-utils/.github/workflows/docker-build-push.yml@main
    secrets: inherit
    with:
       git-repo: ${{ github.repository }}
       git-ref: ${{ github.ref_name }}
       docker-image: gridss
       docker-tag: ${{ inputs.image-tag }}
       artifact-name: docker-resources
       docker-target: gridss
