name: Release and Build gridss Docker image

on:
  workflow_dispatch:
    inputs:
      minor-release:
        description: "Is this a minor release?"
        type: boolean
        required: false
        default: false
      create-release:
        description: "Create a GitHub Release?"
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: write

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/download-docker-resources

  release-and-build:
    needs: [pre-build]
    uses: Ultimagen/ugbio-utils/.github/workflows/release-and-build-docker.yml@DATA-9857-release-and-build-docker-workflow
    secrets: inherit
    with:
      docker-image: gridss
      minor-release: ${{ inputs.minor-release }}
      create-release: ${{ inputs.create-release }}
      base-branch: "ilyasoifer/flow.gridss"
      docker-target: gridss
      artifact-name: docker-resources
